export const CATALOG: { id: string; group: string | null }[] = [
  // high-risk (big-9 expansion + KR additions)
  { id: 'egg', group: 'egg' }, { id: 'milk', group: 'milk' }, { id: 'yogurt', group: 'milk' },
  { id: 'cheese', group: 'milk' }, { id: 'wheat', group: 'wheat' },
  { id: 'peanut', group: 'peanut' }, { id: 'soy', group: 'soy' }, { id: 'tofu', group: 'soy' },
  { id: 'sesame', group: 'sesame' }, { id: 'shrimp', group: 'shellfish' },
  { id: 'crab', group: 'shellfish' }, { id: 'salmon', group: 'fish' },
  { id: 'mackerel', group: 'fish' }, { id: 'almond', group: 'tree_nut' },
  { id: 'walnut', group: 'tree_nut' }, { id: 'cashew', group: 'tree_nut' },
  { id: 'pinenut', group: 'tree_nut' }, { id: 'buckwheat', group: 'buckwheat' },
  // everyday first foods
  { id: 'rice', group: null }, { id: 'oat', group: null }, { id: 'barley', group: null },
  { id: 'corn', group: null }, { id: 'sweetpotato', group: null }, { id: 'potato', group: null },
  { id: 'pumpkin', group: null }, { id: 'zucchini', group: null }, { id: 'carrot', group: null },
  { id: 'broccoli', group: null }, { id: 'cauliflower', group: null },
  { id: 'cabbage', group: null }, { id: 'spinach', group: null }, { id: 'cucumber', group: null },
  { id: 'pea', group: null }, { id: 'onion', group: null }, { id: 'tomato', group: null },
  { id: 'seaweed', group: null }, { id: 'laver', group: null }, { id: 'apple', group: null },
  { id: 'pear', group: null }, { id: 'banana', group: null }, { id: 'avocado', group: null },
  { id: 'blueberry', group: null }, { id: 'strawberry', group: null },
  { id: 'peach', group: null }, { id: 'plum', group: null }, { id: 'mango', group: null },
  { id: 'watermelon', group: null }, { id: 'melon', group: null }, { id: 'grape', group: null },
  { id: 'persimmon', group: null }, { id: 'beef', group: null }, { id: 'chicken', group: null },
  { id: 'pork', group: null },
  // imported from MammaCare v1 (2026-07-28) — high-risk
  { id: 'eggyolk', group: 'egg' }, { id: 'eggwhite', group: 'egg' },
  { id: 'quailegg', group: 'egg' }, { id: 'butter', group: 'milk' },
  { id: 'beansprout', group: 'soy' }, { id: 'blacksoybean', group: 'soy' },
  { id: 'pistachio', group: 'tree_nut' }, { id: 'pecan', group: 'tree_nut' },
  { id: 'hazelnut', group: 'tree_nut' }, { id: 'macadamia', group: 'tree_nut' },
  { id: 'chestnut', group: 'tree_nut' }, { id: 'squid', group: 'shellfish' },
  { id: 'octopus', group: 'shellfish' }, { id: 'smalloctopus', group: 'shellfish' },
  { id: 'abalone', group: 'shellfish' }, { id: 'oyster', group: 'shellfish' },
  { id: 'manilaclam', group: 'shellfish' }, { id: 'cod', group: 'fish' },
  { id: 'pollock', group: 'fish' }, { id: 'spanishmackerel', group: 'fish' },
  { id: 'flounder', group: 'fish' }, { id: 'halibut', group: 'fish' },
  { id: 'croaker', group: 'fish' }, { id: 'seabream', group: 'fish' },
  { id: 'hairtail', group: 'fish' }, { id: 'anchovy', group: 'fish' },
  // imported from MammaCare v1 — everyday foods
  { id: 'radish', group: null }, { id: 'napacabbage', group: null },
  { id: 'bokchoy', group: null }, { id: 'redcabbage', group: null }, { id: 'kale', group: null },
  { id: 'chard', group: null }, { id: 'curledmallow', group: null },
  { id: 'celery', group: null }, { id: 'waterparsley', group: null },
  { id: 'chive', group: null }, { id: 'burdock', group: null }, { id: 'lotusroot', group: null },
  { id: 'eggplant', group: null }, { id: 'bellpepper', group: null }, { id: 'beet', group: null },
  { id: 'ripepumpkin', group: null }, { id: 'shiitake', group: null },
  { id: 'enoki', group: null }, { id: 'oystermushroom', group: null },
  { id: 'buttonmushroom', group: null }, { id: 'kingoystermushroom', group: null },
  { id: 'greenlaver', group: null }, { id: 'kidneybean', group: null },
  { id: 'lentil', group: null }, { id: 'chickpea', group: null }, { id: 'redbean', group: null },
  { id: 'brownrice', group: null }, { id: 'blackrice', group: null },
  { id: 'quinoa', group: null }, { id: 'stickymillet', group: null },
  { id: 'millet', group: null }, { id: 'sorghum', group: null }, { id: 'perilla', group: null },
  { id: 'kiwi', group: null }, { id: 'tangerine', group: null }, { id: 'orange', group: null },
  { id: 'pineapple', group: null }, { id: 'apricot', group: null }, { id: 'cherry', group: null },
  { id: 'jujube', group: null }, { id: 'duck', group: null },
];
